export const CART_ADD_REQUEST = '@cart/ADD_REQUEST';
export const CART_ADD_SUCCESS = '@cart/ADD_SUCCESS';
export const CART_REMOVE = '@cart/REMOVE';
export const CART_UPDATE_AMOUNT_REQUEST = '@cart/UPDATE_AMOUNT_REQUEST';
export const CART_UPDATE_AMOUNT_SUCCESS = '@cart/UPDATE_AMOUNT_SUCCESS';
